/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Community Savings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.navbar}>
        <span className={styles.navbar__label}>💰 Community Savings</span>

        <div className={styles.navbar__right}>
          0x384848329
          <img
            alt="avatar"
            className={styles.avatar}
            src="https://crypto-sbarzotti.com/api/avatar/crypto%20sbarzotti"
          />
        </div>
      </nav>

      <main>
        <section className={styles["balance-grid"]}>
          <div className={styles.card}>
            <span className={styles.card__label}>Available Balance</span>
            <span className={styles.card__value}>2,930ETH</span>
          </div>

          <div className={styles.card}>
            <span className={styles.card__label}>Active Savers</span>
            <span className={styles.card__value}>7</span>
          </div>

          <div className={styles.card}>
            <span className={styles.card__label}>Amount Withdrawn</span>
            <span className={styles.card__value}>2930</span>
          </div>
        </section>

        <section>
          <h2 className={styles["section-header"]}>Recent Transactions</h2>
          <table className={styles.table}>
            <tr>
              <th>S/N</th>
              <th>Address</th>
              <th>Transaction value</th>
              <th>Timestamp</th>
              <th>Action</th>
            </tr>

            <tr>
              <th>#1</th>
              <td>0x27c16e7ED6737Eaf6d86285763A7B2d819B345C4</td>
              <td>0.0002 ETH</td>
              <td>{new Date().toISOString()}</td>
              <td>view on etherscan</td>
            </tr>

            <tr>
              <th>#1</th>
              <td>0x27c16e7ED6737Eaf6d86285763A7B2d819B345C4</td>
              <td>0.0002 ETH</td>
              <td>{new Date().toISOString()}</td>
              <td>view on etherscan</td>
            </tr>

            <tr>
              <th>#1</th>
              <td>0x27c16e7ED6737Eaf6d86285763A7B2d819B345C4</td>
              <td>0.0002 ETH</td>
              <td>{new Date().toISOString()}</td>
              <td>view on etherscan</td>
            </tr>

            <tr>
              <th>#1</th>
              <td>0x27c16e7ED6737Eaf6d86285763A7B2d819B345C4</td>
              <td>0.0002 ETH</td>
              <td>{new Date().toISOString()}</td>
              <td>view on etherscan</td>
            </tr>
          </table>
        </section>
      </main>
    </>
  );
}
